name: My GitHub Actions Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
 build:
   runs-on: ubintu-latest
   steps:
   - name: Checkout code
     uses: actions/checkout@v2
   - name: Build code
     run: <BUOLD>
